version: "3"
services:
  mongo:
    hostname: mongo
    container_name: localmongo
    image: mongo:4.4.4-bionic
    environment:
      - MONGO_INITDB_DATABASE=auth
    expose:
      - 27017
    ports:
      - 27011:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all" ]
  auth-service:
    hostname: auth-service
    container_name: auth-service
    image: auth-service:latest
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - ACCESS_TOKEN_VALID_HOURS=1
      - SECRET_KEY=SecretKey
      - ISSUER=auth.company.com
      - APP_DOMAIN=localhost
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: always
    entrypoint: [ "auth-service" ]